[project]
name = "NotepadLM"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "marcin-banak", email = "marcin.banak03@gmail.com"},
]
dependencies = []
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
